const { v4: uuidv4 } = require("uuid");
const moment = require("moment");

const categories = [
  {
    id: uuidv4(),
    name: "Balance Update",
    color: "#AEC0B1",
    type: "balance",
  },
  {
    id: uuidv4(),
    name: "Food",
    color: "#FF0031",

    type: "expense",
  },
  {
    id: uuidv4(),
    name: "Transport",
    color: "#FF4E00",
    type: "expense",
  },
  {
    id: uuidv4(),
    name: "Clothes",
    color: "#FA0705",
    type: "expense",
  },
  {
    id: uuidv4(),
    name: "Entertainment",
    color: "#FF00B1",
    type: "expense",
  },
  {
    id: uuidv4(),
    name: "Bills",
    color: "#FA8205",
    type: "expense",
  },
  {
    id: uuidv4(),
    name: "Health",
    color: "#FA057D",
    type: "expense",
  },
  {
    id: uuidv4(),
    name: "Salary",
    color: "#16E973",
    type: "income",
  },
  {
    id: uuidv4(),
    name: "Investments",
    color: "#22E916",
    type: "income",
  },
  {
    id: uuidv4(),
    name: "Gift",
    color: "#00FF8F",
    type: "income",
  },
];

const transactions = [
  {
    id: uuidv4(),
    amount: 0,
    date: new Date(),
    description: "Initial balance",
    category: categories[0],
  },
  /*
  {
    id: uuidv4(),
    amount: 100.5,
    date: new Date("2023-01-01"),
    description: "Salad",
    category: categories[1],
  },
  {
    id: uuidv4(),
    amount: 150.0,
    date: new Date("2023-01-02"),
    description: "Bus fare",
    category: categories[2],
  },
  {
    id: uuidv4(),
    amount: 75.0,
    date: new Date("2023-01-03"),
    description: "Shoes",
    category: categories[3],
  },
  {
    id: uuidv4(),
    amount: 50.0,
    date: new Date("2023-01-03"),
    description: "Concert tickets",
    category: categories[4],
  },
  {
    id: uuidv4(),
    amount: 200.0,
    date: new Date("2023-01-01"),
    description: "Utilities",
    category: categories[5],
  },
  {
    id: uuidv4(),
    amount: 150.0,
    date: new Date("2023-01-06"),
    description: "Prescription",
    category: categories[6],
  },
  {
    id: uuidv4(),
    amount: 2500.0,
    date: new Date("2023-01-07"),
    description: "Paycheck",
    category: categories[7],
  },
  {
    id: uuidv4(),
    amount: 500.0,
    date: new Date("2023-01-08"),
    description: "Dividend",
    category: categories[8],
  },
  {
    id: uuidv4(),
    amount: 100.0,
    date: new Date("2023-01-09"),
    description: "Birthday gift",
    category: categories[9],
  },
  {
    id: uuidv4(),
    amount: 20.0,
    date: new Date("2023-01-03"),
    description: "Snacks",
    category: categories[1],
  },
  {
    id: uuidv4(),
    amount: 50.0,
    date: new Date("2023-01-11"),
    description: "Gas",
    category: categories[2],
  },
  {
    id: uuidv4(),
    amount: 75.0,
    date: new Date("2023-01-05"),
    description: "Shirt",
    category: categories[3],
  },
  {
    id: uuidv4(),
    amount: 100.0,
    date: new Date("2023-01-13"),
    description: "Movie tickets",
    category: categories[4],
  },
  {
    id: uuidv4(),
    amount: 150.0,
    date: new Date("2023-01-03"),
    description: "Internet and cable",
    category: categories[5],
  },
  {
    id: uuidv4(),
    amount: 75.0,
    date: new Date("2023-01-15"),
    description: "Doctor visit",
    category: categories[6],
  },
  {
    id: uuidv4(),
    amount: 3000.0,
    date: new Date("2023-01-11"),
    description: "Paycheck",
    category: categories[7],
  },
  {
    id: uuidv4(),
    amount: 500.0,
    date: new Date("2023-01-17"),
    description: "Stock sale",
    category: categories[8],
  },
  {
    id: uuidv4(),
    amount: 50.0,
    date: new Date("2023-01-20"),
    description: "Gift card",
    category: categories[9],
  },
  {
    id: uuidv4(),
    amount: 20.0,
    date: new Date("2023-01-19"),
    description: "Apples",
    category: categories[1],
  },
  {
    id: uuidv4(),
    amount: 50.0,
    date: new Date("2023-01-20"),
    description: "Taxi",
    category: categories[2],
  },
  {
    id: uuidv4(),
    amount: 75.0,
    date: new Date("2023-01-20"),
    description: "Pants",
    category: categories[3],
  },
  {
    id: uuidv4(),
    amount: 100.0,
    date: new Date("2023-01-22"),
    description: "Concert tickets",
    category: categories[4],
  },
  {
    id: uuidv4(),
    amount: 150.0,
    date: new Date("2023-01-23"),
    description: "Electricity",
    category: categories[5],
  },
  {
    id: uuidv4(),
    amount: 75.0,
    date: new Date("2023-01-24"),
    description: "Prescription",
    category: categories[6],
  },
  {
    id: uuidv4(),
    amount: 400.0,
    date: new Date("2023-01-20"),
    description: "Freelance work",
    category: categories[7],
  },
  {
    id: uuidv4(),
    amount: 100.0,
    date: new Date("2023-01-26"),
    description: "Interest income",
    category: categories[8],
  },
  {
    id: uuidv4(),
    amount: 50.0,
    date: new Date("2023-01-20"),
    description: "Gift",
    category: categories[9],
  },
  {
    id: uuidv4(),
    amount: 20.0,
    date: new Date("2023-01-28"),
    description: "Chips",
    category: categories[1],
  },
  {
    id: uuidv4(),
    amount: 50.0,
    date: new Date("2023-01-29"),
    description: "Train tickets",
    category: categories[2],
  },
  {
    id: uuidv4(),
    amount: 75.0,
    date: new Date("2023-01-02"),
    description: "Sneakers",
    category: categories[3],
  },
  {
    id: uuidv4(),
    amount: 100.0,
    date: new Date("2023-01-31"),
    description: "Theater tickets",
    category: categories[4],
  },
  */
];

const initialUserState = {
  transactions,
  categories,
};

module.exports = initialUserState;
